# run the below command in terminal with some non zero value(1 to 3) to get anti-aliased font.
# defaults write org.alacritty AppleFontSmoothing -int 0

[general] # Go to line 41 and comment out the background color
import = [
# "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
# "~/.config/alacritty/themes/themes/prime.toml"
# "~/.config/alacritty/themes/themes/ayu_dark.toml"
# "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[env]
TERM="xterm-256color"
# [window]
# padding.x = 10
# padding.y = 10
# opacity = "0.85"
# blur =true
# decorations = "Buttonless"
# startup_mode = "SimpleFullscreen"

[colors.cursor]
# text = "#000000"    # The color of the text underneath the cursor
# cursor = "#ffffff"  # The color of the cursor itself
# cursor = "#fff000"  # The color of the cursor itself

# [cursor]
# style.blinking = "on"
# blink_interval = 500

[colors]
# If `true`, bold text is drawn using the bright color variants.
# draw_bold_text_with_bright_colors = true
# decorations = "Transparent"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "Iosevka Nerd Font"
# normal.family = "Maple Mono NF"
# normal.family = "BlexMono Nerd Font"
# normal.family = "FiraCode Nerd Font"
# normal.family = "Fira Mono"
# normal.family = "CommitMono Nerd Font"
normal.family= "DejaVuSansM Nerd Font Mono"
normal.style = "Regular"
# normal.family = "SourceCodePro Nerd Font"
# normal.family = "JetBrains Mono"
# normal.family = "JetBrainsMono Nerd Font"
size = 18


[colors.primary]
# background = '#000000' #Comment this out to get the theme background color
background = "#1B1E20" #grey go to primeagen
# background = "#16161e" #tokyonight dark
# background = "#1a1b26" #tokyonight
# background = "#090300" #reddish black
# background = "#181818" # gruber dark

[window.padding]
x = 5
y = 0

[window.dimensions]
columns = 250
lines = 90

[window.position]
x = 800
y = 150


[keyboard]
bindings = [
  { key = "F",     mods = "Alt", action = "ToggleSimpleFullscreen" },
  { key = "Q",     mods = "Command",  action = "None" },
  # Bindings below allow word skipping with "Alt + Arrow" in tmux,
  # but interfere with pane resizing using Alt. Instead, use Ctrl + Arrow
  # to resize panes (this alternative is available by default).
  { key = "Right",  mods = "Alt", chars = "\u001BF" },
  { key = "Left",   mods = "Alt", chars = "\u001BB" },

]


[mouse]
hide_when_typing = true

[window]
# startup_mode = "SimpleFullscreen"
# opacity=0.9
# blur = true
option_as_alt = "Both"











# [general]
# import = [
# # "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
# # "~/.config/alacritty/themes/themes/prime.toml"
# # "~/.config/alacritty/themes/themes/ayu_dark.toml"
# # "~/.config/alacritty/themes/themes/blood_moon.toml"
# ]
#
# [env]
# TERM = "xterm-256color"
#
# [font]
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# size = 13.5
#
# offset = { x = 0, y = 0 }
# glyph_offset = { x = 0, y = 0 }
#
# [colors.primary]
# background = "#1d1f21"
#
# [window]
# padding = { x = 5, y = 0 }
# decorations = "None"
# option_as_alt = "Both"
#
# [window.dimensions]
# columns = 250
# lines = 90
#
# [window.position]
# x = 800
# y = 150
#
# [keyboard]
# bindings = [
# { key = "F", mods = "Alt", action = "ToggleSimpleFullscreen" },
# { key = "Q", mods = "Command", action = "None" },
# { key = "Right", mods = "Alt", chars = "\u001BF" },
# { key = "Left", mods = "Alt", chars = "\u001BB" }
# ]
#
# [mouse]
# hide_when_typing = true
#
