return {
	-- {
	-- 	"saghen/blink.cmp",
	-- 	event = { "LspAttach" },
	-- 	dependencies = {
	-- 		"folke/lazydev.nvim",
	-- 		{ "rafamadriz/friendly-snippets" },
	-- 		ft = "lua",
	-- 		opts = {
	-- 			library = {
	-- 				{ path = "${3rd}/luv/library", words = { "vim%.uv" } },
	-- 			},
	-- 		},
	-- 	},
	-- 	version = "v0.*",
	-- 	opts = {
	-- 		keymap = { preset = "enter" },
	-- 		sources = {
	-- 			default = {
	-- 				"lsp",
	-- 				"path",
	-- 				"snippets",
	-- 				"buffer",
	-- 				"lazydev",
	-- 			},
	-- 			cmdline = {},
	-- 			providers = {
	-- 				lsp = { fallbacks = { "lazydev" } },
	-- 				lazydev = { name = "LazyDev", module = "lazydev.integrations.blink" },
	-- 			},
	-- 		},
	--
	-- 		completion = {
	-- 			accept = { auto_brackets = { enabled = false } },
	-- 			trigger = {
	-- 				show_on_insert_on_trigger_character = false,
	-- 			},
	-- 			menu = {
	-- 				border = vim.g.border_style,
	-- 				scrolloff = 0,
	-- 				scrollbar = true,
	-- 				-- draw = {
	-- 				-- columns = { { "kind_icon" }, { "label", "label_description", gap = 0 } },
	--
	-- 				-- draw = {
	-- 				-- 	padding = 0,
	-- 				-- 	gap = 1,
	-- 				-- treesitter = true,
	-- 				draw = {
	-- 					-- columns = { { "item_idx" }, { "kind_icon" }, { "label", "label_description", gap = 1 } },
	-- 					columns = { { "item_idx" }, { "label", "label_description", gap = 1 } },
	-- 					components = {
	-- 						item_idx = {
	-- 							text = function(ctx)
	-- 								return tostring(ctx.idx)
	-- 							end,
	-- 							highlight = "BlinkCmpItemIdx", -- optional, only if you want to change its color
	-- 						},
	-- 					},
	-- 				},
	-- 			},
	-- 			-- },
	--
	-- 			documentation = {
	-- 				auto_show_delay_ms = 0,
	-- 				auto_show = true,
	-- 				window = {
	-- 					border = vim.g.border_style,
	-- 				},
	-- 			},
	-- 		},
	--
	-- 		signature = {
	-- 			enabled = true,
	-- 		},
	-- 	},
	-- },
}
