return {
    -- "jose-elias-alvarez/null-ls.nvim",
    -- dependencies = { "nvim-lua/plenary.nvim" },
    -- config = function()
    --     local null_ls = require("null-ls")
    --
    --     null_ls.setup({
    --         sources = {
    --             -- Linting with Pyright
    --             null_ls.builtins.diagnostics.ruff,
    --
    --             -- Formatting with Black
    --             null_ls.builtins.formatting.black.with({
    --                 extra_args = { "--line-length", "88" }, -- Customize line length
    --             }),
    --
    --             -- Type checking with Mypy
    --             null_ls.builtins.diagnostics.mypy.with({
    --                 extra_args = {}, -- Enable strict mode
    --             }),
    --         },
    --         -- Optional: Attach formatting functionality
    --         on_attach = function(client, bufnr)
    --             if client.supports_method("textDocument/formatting") then
    --                 vim.api.nvim_buf_set_keymap(bufnr, "n", "<leader>f",
    --                     "<cmd>lua vim.lsp.buf.format({ async = true })<CR>", { noremap = true, silent = true })
    --             end
    --         end,
    --     })
    -- end,
}
