# #!/bin/bash
#
# # Fixed wallpaper selector with better error handling and logging
# # Usage: ./wallpaper-selector-fixed.sh
#
# # Configuration
# WALLPAPER_DIR="$HOME/.config/backgrounds/"
# HYPRPAPER_CONFIG="$HOME/.config/hypr/hyprpaper.conf"
# CACHE_DIR="$HOME/.cache/wallpaper-selector"
# LOG_FILE="$HOME/.cache/wallpaper-selector.log"
#
# # Logging function
# log() {
#     echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
# }
#
# # Error handling function
# error_exit() {
#     log "ERROR: $1"
#     notify-send "Wallpaper Selector Error" "$1" -u critical
#     exit 1
# }
#
# # Success notification function
# success_notify() {
#     log "SUCCESS: $1"
#     notify-send "Wallpaper Selector" "$1" -u normal
# }
#
# # Check if running in Wayland
# if [ -z "$WAYLAND_DISPLAY" ]; then
#     error_exit "Not running in Wayland session"
# fi
#
# log "Starting wallpaper selector..."
#
# # Create necessary directories
# mkdir -p "$CACHE_DIR" "$(dirname "$HYPRPAPER_CONFIG")" "$(dirname "$LOG_FILE")"
#
# # Check if wallpaper directory exists
# if [ ! -d "$WALLPAPER_DIR" ]; then
#     log "Creating wallpaper directory: $WALLPAPER_DIR"
#     mkdir -p "$WALLPAPER_DIR"
#     error_exit "Wallpaper directory was empty. Please add some wallpapers to $WALLPAPER_DIR"
# fi
#
# # Check dependencies with specific error messages
# if ! command -v rofi &> /dev/null; then
#     error_exit "rofi not found. Install with: sudo pacman -S rofi-wayland"
# fi
#
# if ! command -v hyprpaper &> /dev/null; then
#     error_exit "hyprpaper not found. Install with: sudo pacman -S hyprpaper"
# fi
#
# # Get list of wallpapers
# mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.bmp" -o -iname "*.tiff" -o -iname "*.webp" \) -printf "%f\n" 2>/dev/null | sort)
#
# if [ ${#wallpapers[@]} -eq 0 ]; then
#     error_exit "No wallpaper files found in $WALLPAPER_DIR. Supported formats: jpg, png, bmp, tiff, webp"
# fi
#
# log "Found ${#wallpapers[@]} wallpapers"
#
# # Simple rofi selection (without previews for now to avoid issues)
# selected_wallpaper=$(printf '%s\n' "${wallpapers[@]}" | rofi -dmenu -i -p "Select Wallpaper (${#wallpapers[@]} found)" \
#     -theme-str 'window {width: 50%; height: 60%;}' \
#     -theme-str 'listview {lines: 10;}' \
#     -theme-str 'element {padding: 8px;}' 2>/dev/null)
#
# # Check if user cancelled selection
# if [ -z "$selected_wallpaper" ]; then
#     log "User cancelled selection"
#     exit 0
# fi
#
# # Verify selected wallpaper exists
# wallpaper_path="$WALLPAPER_DIR/$selected_wallpaper"
# if [ ! -f "$wallpaper_path" ]; then
#     error_exit "Selected wallpaper not found: $wallpaper_path"
# fi
#
# log "Selected wallpaper: $selected_wallpaper"
#
# # Get monitors - with multiple fallback methods
# monitors=""
# if command -v hyprctl &> /dev/null && [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
#     log "Getting monitors via hyprctl..."
#     monitors=$(hyprctl monitors -j 2>/dev/null | jq -r '.[].name' 2>/dev/null | tr '\n' ' ')
# fi
#
# # Fallback methods if hyprctl fails
# if [ -z "$monitors" ]; then
#     log "hyprctl failed, trying wlr-randr..."
#     if command -v wlr-randr &> /dev/null; then
#         monitors=$(wlr-randr 2>/dev/null | grep "^[A-Z]" | awk '{print $1}' | tr '\n' ' ')
#     fi
# fi
#
# # Final fallback - common monitor names
# if [ -z "$monitors" ]; then
#     log "Using fallback monitor detection..."
#     monitors="DP-1 DP-2 HDMI-A-1 eDP-1"
# fi
#
# log "Detected monitors: $monitors"
#
# # Kill existing hyprpaper process gracefully
# if pgrep -x hyprpaper > /dev/null; then
#     log "Stopping existing hyprpaper..."
#     pkill -TERM hyprpaper
#     sleep 1
#
#     # Force kill if still running
#     if pgrep -x hyprpaper > /dev/null; then
#         pkill -KILL hyprpaper
#         sleep 1
#     fi
# fi
#
# # Create hyprpaper configuration
# log "Creating hyprpaper configuration..."
# {
#     echo "# Generated by wallpaper selector on $(date)"
#     echo "preload = $wallpaper_path"
#     echo ""
#
#     # Apply to all detected monitors
#     for monitor in $monitors; do
#         if [ -n "$monitor" ]; then
#             echo "wallpaper = $monitor,$wallpaper_path"
#         fi
#     done
#
#     echo ""
#     echo "splash = false"
#     echo "ipc = on"
# } > "$HYPRPAPER_CONFIG"
#
# log "Configuration written to $HYPRPAPER_CONFIG"
#
# # Start hyprpaper with error handling
# log "Starting hyprpaper..."
# if hyprpaper > "$CACHE_DIR/hyprpaper_output.log" 2>&1 & then
#     hyprpaper_pid=$!
#
#     # Wait a moment for hyprpaper to initialize
#     sleep 2
#
#     # Check if hyprpaper is still running
#     if kill -0 "$hyprpaper_pid" 2>/dev/null; then
#         success_notify "Applied wallpaper: $selected_wallpaper"
#
#         # Save current wallpaper for persistence
#         echo "$wallpaper_path" > "$HOME/.config/hypr/current_wallpaper"
#         echo "$(date): $selected_wallpaper" >> "$HOME/.config/hypr/wallpaper_history.log"
#
#         log "Wallpaper applied successfully"
#     else
#         error_exit "hyprpaper failed to start. Check $CACHE_DIR/hyprpaper_output.log for details"
#     fi
# else
#     error_exit "Failed to start hyprpaper process"
# fi
#
# log "Wallpaper selector completed successfully"
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#










#!/bin/bash

# Simple wallpaper selector for Hyprland
# Usage: ./wallpaper-selector.sh

# Configuration
WALLPAPER_DIR="$HOME/.config/backgrounds/"
HYPRPAPER_CONFIG="$HOME/.config/hypr/hyprpaper.conf"
CACHE_DIR="$HOME/.cache/wallpaper-selector"

# Error handling function
error_exit() {
    notify-send "Wallpaper Selector Error" "$1" -u critical
    exit 1
}

# Success notification function
success_notify() {
    notify-send "Wallpaper Selector" "$1" -u normal
}

# Check if running in Wayland
if [ -z "$WAYLAND_DISPLAY" ]; then
    error_exit "Not running in Wayland session"
fi

# Create necessary directories
mkdir -p "$CACHE_DIR" "$(dirname "$HYPRPAPER_CONFIG")"

# Check if wallpaper directory exists
if [ ! -d "$WALLPAPER_DIR" ]; then
    mkdir -p "$WALLPAPER_DIR"
    error_exit "Wallpaper directory was empty. Please add some wallpapers to $WALLPAPER_DIR"
fi

# Check dependencies
if ! command -v rofi &> /dev/null; then
    error_exit "rofi not found. Install with: sudo pacman -S rofi-wayland"
fi

if ! command -v hyprpaper &> /dev/null; then
    error_exit "hyprpaper not found. Install with: sudo pacman -S hyprpaper"
fi

# Get list of wallpapers
mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.bmp" -o -iname "*.tiff" -o -iname "*.webp" \) -printf "%f\n" 2>/dev/null | sort)

if [ ${#wallpapers[@]} -eq 0 ]; then
    error_exit "No wallpaper files found in $WALLPAPER_DIR. Supported formats: jpg, png, bmp, tiff, webp"
fi

# Wallpaper selection
selected_wallpaper=$(printf '%s\n' "${wallpapers[@]}" | rofi -dmenu -i -p "Select Wallpaper (${#wallpapers[@]} found)" \
    -theme-str 'window {width: 50%; height: 60%;}' \
    -theme-str 'listview {lines: 10;}' \
    -theme-str 'element {padding: 8px;}')

# Check if user cancelled selection
if [ -z "$selected_wallpaper" ]; then
    exit 0
fi

# Verify selected wallpaper exists
wallpaper_path="$WALLPAPER_DIR/$selected_wallpaper"
if [ ! -f "$wallpaper_path" ]; then
    error_exit "Selected wallpaper not found: $wallpaper_path"
fi

# Get monitors
monitors=""
if command -v hyprctl &> /dev/null && [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
    monitors=$(hyprctl monitors -j 2>/dev/null | jq -r '.[].name' 2>/dev/null | tr '\n' ' ')
fi

if [ -z "$monitors" ] && command -v wlr-randr &> /dev/null; then
    monitors=$(wlr-randr 2>/dev/null | grep "^[A-Z]" | awk '{print $1}' | tr '\n' ' ')
fi

if [ -z "$monitors" ]; then
    monitors="DP-1 DP-2 HDMI-A-1 eDP-1"
fi

# Kill existing hyprpaper
if pgrep -x hyprpaper > /dev/null; then
    pkill -TERM hyprpaper
    sleep 1
    if pgrep -x hyprpaper > /dev/null; then
        pkill -KILL hyprpaper
        sleep 1
    fi
fi

# Create hyprpaper config
{
    echo "# Generated by wallpaper selector"
    echo "preload = $wallpaper_path"
    echo ""
    for monitor in $monitors; do
        if [ -n "$monitor" ]; then
            echo "wallpaper = $monitor,$wallpaper_path"
        fi
    done
    echo ""
    echo "splash = false"
    echo "ipc = on"
} > "$HYPRPAPER_CONFIG"

# Start hyprpaper
if hyprpaper > /dev/null 2>&1 & then
    hyprpaper_pid=$!
    sleep 2
    if kill -0 "$hyprpaper_pid" 2>/dev/null; then
        success_notify "Applied wallpaper: $selected_wallpaper"
        echo "$wallpaper_path" > "$HOME/.config/hypr/current_wallpaper"
        echo "$(date): $selected_wallpaper" >> "$HOME/.config/hypr/wallpaper_history.log"
    else
        error_exit "hyprpaper failed to start. Check hyprpaper logs."
    fi
else
    error_exit "Failed to start hyprpaper process"
fi

