# preload = /home/thebhuvnesh/.config/backgrounds/train.jxl
# wallpaper = HDMI-A-1,/home/thebhuvnesh/.config/backgrounds/train.jxl
# wallpaper = eDP-1,/home/thebhuvnesh/.config/backgrounds/train.jxl
# preload = /home/thebhuvnesh/.config/backgrounds/hyprwall.png
# wallpaper = HDMI-A-1,/home/thebhuvnesh/.config/backgrounds/hyprwall.png
# wallpaper = eDP-1,/home/thebhuvnesh/.config/backgrounds/hyprwall.png
preload = /home/thebhuvnesh/.config/backgrounds/aegis-pointing.png
wallpaper = HDMI-A-1,/home/thebhuvnesh/.config/backgrounds/aegis-pointing.png
wallpaper = eDP-1,/home/thebhuvnesh/.config/backgrounds/aegis-pointing.png
# preload = /home/thebhuvnesh/.config/backgrounds/yellow_red_blue.png
# wallpaper = HDMI-A-1,/home/thebhuvnesh/.config/backgrounds/yellow_red_blue.png
# wallpaper = eDP-1,/home/thebhuvnesh/.config/backgrounds/yellow_red_blue.png
# preload = /home/thebhuvnesh/.config/backgrounds/f2.jpg
# wallpaper = HDMI-A-1,/home/thebhuvnesh/.config/backgrounds/f2.jpg
# wallpaper = eDP-1,/home/thebhuvnesh/.config/backgrounds/f2.jpg
